# Generated by Django 6.0.2 on 2026-02-26 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_book_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('Fantasy', 'FANTASY CATEGORY'), ('Mystic', 'MYSTIC CATEGORY'), ('Biography', 'BIOGRAPHY CATEGORY'), ('N/A', 'UNRECOGNISED CATEGORY')], default='N/A', max_length=30),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
