# Generated by Django 6.0.2 on 2026-02-26 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_alter_book_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('Fantasy', 'FANTASY CATEGORY'), ('Mystic', 'MYSTIC CATEGORY'), ('Biography', 'BIOGRAPHY CATEGORY'), ('N/A', 'UNRECOGNISED CATEGORY')], default='N/A', help_text="Категория книги из списка предложенных. Если неизвестна, выберите 'N/A'", max_length=30, verbose_name='Категория книги'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(verbose_name='Описание книги'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Цена книги в евро. Должно быть больше 0', max_digits=5, null=True, verbose_name='Цена книги'),
        ),
        migrations.AlterField(
            model_name='book',
            name='published_date',
            field=models.DateTimeField(verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(error_messages={'blank': 'Сожалеем, но книгу нельзя создать без названия книги.', 'unique': 'Кажется книга с таким названием уже существует.'}, max_length=125, unique=True, verbose_name='Название книги'),
        ),
    ]
