# Generated by Django 6.0.2 on 2026-04-22 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_user_deleted_user_deleted_at_alter_book_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['username'], 'permissions': [('can_get_statistic', 'Can Get Statistic')]},
        ),
    ]
